import type { Product } from "@/types/product.type";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    sku: "ESP-001",
    name: "Classic Espresso",
    description: "Bold and intense with rich crema",
    imageUrl: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400",
    content: "Premium espresso beans, single shot",
    minPrice: 3.0,
    maxPrice: 4.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    id: 2,
    sku: "LAT-001",
    name: "Smooth Latte",
    description: "Creamy perfection with velvety foam",
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
    content: "Espresso with steamed milk and foam",
    minPrice: 4.0,
    maxPrice: 5.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    id: 3,
    sku: "MAC-001",
    name: "Caramel Macchiato",
    description: "Sweet caramel meets bold espresso",
    imageUrl: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400",
    content: "Espresso, steamed milk, vanilla syrup, caramel drizzle",
    minPrice: 4.5,
    maxPrice: 5.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    id: 4,
    sku: "ICE-001",
    name: "Iced Americano",
    description: "Refreshing and bold over ice",
    imageUrl: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400",
    content: "Espresso shots over ice with cold water",
    minPrice: 3.5,
    maxPrice: 4.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    id: 5,
    sku: "CAP-001",
    name: "Vanilla Cappuccino",
    description: "Classic with a hint of vanilla",
    imageUrl: null,
    content: "Espresso, steamed milk, vanilla syrup, foam",
    minPrice: 4.25,
    maxPrice: 5.25,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    id: 6,
    sku: "MOC-001",
    name: "Mocha Delight",
    description: "Rich chocolate meets premium coffee",
    imageUrl: null,
    content: "Espresso, steamed milk, chocolate syrup, whipped cream",
    minPrice: 4.75,
    maxPrice: 5.75,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    id: 7,
    sku: "TEA-001",
    name: "Green Tea Latte",
    description: "Smooth matcha green tea with steamed milk",
    imageUrl: null,
    content: "Premium matcha powder, steamed milk, sweetener",
    minPrice: 4.5,
    maxPrice: 5.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: 8,
    sku: "TEA-002",
    name: "Earl Grey Tea",
    description: "Classic bergamot-infused black tea",
    imageUrl: null,
    content: "Premium Earl Grey tea leaves",
    minPrice: 3.0,
    maxPrice: 4.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: 9,
    sku: "SMO-001",
    name: "Berry Blast Smoothie",
    description: "Mixed berries with yogurt",
    imageUrl: null,
    content: "Strawberries, blueberries, raspberries, yogurt, honey",
    minPrice: 5.0,
    maxPrice: 6.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-20").toISOString(),
    updated_at: new Date("2024-01-20").toISOString(),
  },
  {
    id: 10,
    sku: "SMO-002",
    name: "Tropical Paradise",
    description: "Mango, pineapple, and banana smoothie",
    imageUrl: null,
    content: "Fresh mango, pineapple, banana, coconut milk",
    minPrice: 5.5,
    maxPrice: 7.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-20").toISOString(),
    updated_at: new Date("2024-01-20").toISOString(),
  },
  {
    id: 11,
    sku: "PAS-001",
    name: "Chocolate Croissant",
    description: "Buttery croissant with rich chocolate",
    imageUrl: null,
    content: "Fresh baked croissant, dark chocolate filling",
    minPrice: 3.5,
    maxPrice: 4.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-25").toISOString(),
    updated_at: new Date("2024-01-25").toISOString(),
  },
  {
    id: 12,
    sku: "PAS-002",
    name: "Blueberry Muffin",
    description: "Moist muffin packed with fresh blueberries",
    imageUrl: null,
    content: "Fresh blueberries, flour, sugar, eggs, butter",
    minPrice: 3.0,
    maxPrice: 4.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-01-25").toISOString(),
    updated_at: new Date("2024-01-25").toISOString(),
  },
  {
    id: 13,
    sku: "SAN-001",
    name: "Turkey Club Sandwich",
    description: "Triple-decker with turkey, bacon, and avocado",
    imageUrl: null,
    content: "Sliced turkey, bacon, avocado, lettuce, tomato, mayo",
    minPrice: 7.5,
    maxPrice: 9.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-01").toISOString(),
    updated_at: new Date("2024-02-01").toISOString(),
  },
  {
    id: 14,
    sku: "SAN-002",
    name: "Veggie Wrap",
    description: "Healthy wrap with grilled vegetables",
    imageUrl: null,
    content: "Grilled zucchini, peppers, hummus, spinach, feta",
    minPrice: 6.5,
    maxPrice: 8.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-01").toISOString(),
    updated_at: new Date("2024-02-01").toISOString(),
  },
  {
    id: 15,
    sku: "COL-001",
    name: "Vanilla Cold Brew",
    description: "Smooth cold brew with vanilla",
    imageUrl: null,
    content: "Cold brew coffee, vanilla syrup, ice",
    minPrice: 4.5,
    maxPrice: 5.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-05").toISOString(),
    updated_at: new Date("2024-02-05").toISOString(),
  },
  {
    id: 16,
    sku: "COL-002",
    name: "Caramel Cold Brew",
    description: "Cold brew with caramel sweetness",
    imageUrl: null,
    content: "Cold brew coffee, caramel syrup, cream, ice",
    minPrice: 5.0,
    maxPrice: 6.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-05").toISOString(),
    updated_at: new Date("2024-02-05").toISOString(),
  },
  {
    id: 17,
    sku: "FRA-001",
    name: "Mocha Frappuccino",
    description: "Blended coffee with chocolate",
    imageUrl: null,
    content: "Coffee, chocolate, ice, whipped cream",
    minPrice: 5.5,
    maxPrice: 6.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-10").toISOString(),
    updated_at: new Date("2024-02-10").toISOString(),
  },
  {
    id: 18,
    sku: "FRA-002",
    name: "Caramel Frappuccino",
    description: "Blended caramel coffee delight",
    imageUrl: null,
    content: "Coffee, caramel, ice, whipped cream, caramel drizzle",
    minPrice: 5.5,
    maxPrice: 6.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-10").toISOString(),
    updated_at: new Date("2024-02-10").toISOString(),
  },
  {
    id: 19,
    sku: "HOT-001",
    name: "Classic Hot Chocolate",
    description: "Rich and creamy hot chocolate",
    imageUrl: null,
    content: "Premium cocoa, steamed milk, whipped cream",
    minPrice: 4.0,
    maxPrice: 5.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-12").toISOString(),
    updated_at: new Date("2024-02-12").toISOString(),
  },
  {
    id: 20,
    sku: "HOT-002",
    name: "White Hot Chocolate",
    description: "Smooth white chocolate beverage",
    imageUrl: null,
    content: "White chocolate, steamed milk, vanilla, whipped cream",
    minPrice: 4.5,
    maxPrice: 5.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-12").toISOString(),
    updated_at: new Date("2024-02-12").toISOString(),
  },
  {
    id: 21,
    sku: "SEA-001",
    name: "Pumpkin Spice Latte",
    description: "Fall favorite with pumpkin and spices",
    imageUrl: null,
    content: "Espresso, steamed milk, pumpkin spice syrup, whipped cream",
    minPrice: 5.0,
    maxPrice: 6.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-15").toISOString(),
    updated_at: new Date("2024-02-15").toISOString(),
  },
  {
    id: 22,
    sku: "SEA-002",
    name: "Peppermint Mocha",
    description: "Holiday favorite with peppermint and chocolate",
    imageUrl: null,
    content: "Espresso, steamed milk, chocolate, peppermint syrup",
    minPrice: 5.0,
    maxPrice: 6.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-15").toISOString(),
    updated_at: new Date("2024-02-15").toISOString(),
  },
  {
    id: 23,
    sku: "BRE-001",
    name: "Breakfast Burrito",
    description: "Hearty breakfast wrap with eggs and bacon",
    imageUrl: null,
    content: "Scrambled eggs, bacon, cheese, peppers, tortilla",
    minPrice: 6.0,
    maxPrice: 7.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-18").toISOString(),
    updated_at: new Date("2024-02-18").toISOString(),
  },
  {
    id: 24,
    sku: "BRE-002",
    name: "Avocado Toast",
    description: "Trendy toast with fresh avocado",
    imageUrl: null,
    content: "Toasted sourdough, mashed avocado, cherry tomatoes, feta",
    minPrice: 7.0,
    maxPrice: 8.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-18").toISOString(),
    updated_at: new Date("2024-02-18").toISOString(),
  },
  {
    id: 25,
    sku: "NON-001",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    imageUrl: null,
    content: "100% fresh oranges",
    minPrice: 4.0,
    maxPrice: 5.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-20").toISOString(),
    updated_at: new Date("2024-02-20").toISOString(),
  },
  {
    id: 26,
    sku: "NON-002",
    name: "Strawberry Lemonade",
    description: "Refreshing strawberry lemonade",
    imageUrl: null,
    content: "Fresh strawberries, lemon juice, sugar, water",
    minPrice: 3.5,
    maxPrice: 4.5,
    is_active: true,
    is_deleted: false,
    created_at: new Date("2024-02-20").toISOString(),
    updated_at: new Date("2024-02-20").toISOString(),
  },
];

// Temporary mock mapping: Product ID -> Category ID
export const PRODUCT_CATEGORY_MAP: Record<number, number> = {
  1: 1, // Espresso
  2: 2, // Latte
  3: 2, // Latte
  4: 3, // Iced Coffee
  5: 2, // Latte
  6: 4, // Specialty
  7: 5, // Tea
  8: 5, // Tea
  9: 6, // Smoothies
  10: 6, // Smoothies
  11: 7, // Pastries
  12: 7, // Pastries
  13: 8, // Sandwiches
  14: 8, // Sandwiches
  15: 9, // Cold Brew
  16: 9, // Cold Brew
  17: 10, // Frappuccino
  18: 10, // Frappuccino
  19: 11, // Hot Chocolate
  20: 11, // Hot Chocolate
  21: 12, // Seasonal
  22: 12, // Seasonal
  23: 13, // Breakfast
  24: 13, // Breakfast
  25: 14, // Non-Coffee
  26: 14, // Non-Coffee
};
