export const ROUTER_URL = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  PRODUCTS: "/products",
  CLIENT: "/client",
  PRODUCT_DETAIL: "products/:slug",
  CLIENT_ROUTER: {
    LOGIN: "/client/login",
    REGISTER: "register",
    CART: "cart",
  },

  ADMIN: "/admin",
  ADMIN_ROUTER: {
    LOGIN: "/admin/login",
    DASHBOARD: "dashboard",
    USER_CONTROL: "user-control",
    USER_CONTROL_CREATE: "user-control/create",
    USER_CONTROL_EDIT: "user-control/:id/edit",
    FRANCHISES: "franchises",
    FRANCHISES_CREATE: "franchises/create",
    FRANCHISES_EDIT: "franchises/:id/edit",
    FRANCHISES_DETAIL: "franchises/:id",
    INVENTORY: "inventory",
    INVENTORY_LOW_STOCK: "inventory/low-stock",
    CATEGORIES: "categories",
    CATEGORIES_CREATE: "categories/create",
    CATEGORIES_EDIT: "categories/:id/edit",
    PRODUCTS: "products",
    PRODUCTS_CREATE: "products/create",
    PRODUCTS_EDIT: "products/:id/edit",
    PRODUCTS_DETAIL: "products/:id",
  },
};
