export const ROUTER_URL = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOCATIONS: "/locations",
  MENU: "menu",
  MENU_PRODUCT_DETAIL: "menu/product/:franchiseId/:productId",

  PRODUCTS: "/products",
  CLIENT: "/client",
  PRODUCT_DETAIL: "products/:slug",
  CLIENT_ROUTER: {
    LOGIN: "/client/login",
    FORGOT_PASSWORD: "/client/forgot-password",
    REGISTER: "/client/register",
    CHANGE_PASSWORD: "/client/change-password",
    CART: "cart",
    CHECKOUT: "checkout",
    PRODUCTS: "products",
    PRODUCT_DETAIL: "products/:slug",
    PAYMENT: "payment",
    PAYMENT_NEW: "payment-new",
    PAYMENT_QR: "payment/qr",
    PAYMENT_SUCCESS: "payment/success",
  },
  VERIFY_EMAIL: "verify-customer-email/:id",
  ACCOUNT: "/account",
  ACCOUNT_ROUTER: {
    MY_PROFILE: "my-profile",
    MY_ORDER: "my-order",
  },

  ADMIN: "/admin",
  VERIFIED_ACCOUNT: "verify-email/:id",
  ADMIN_ROUTER: {
    LOGIN: "/admin/login",
    Forgot_PASSWORD: "/admin/forgot-password",
    MY_PROFILE: "my-profile",
    CHANGE_PASSWORD: "change-password",
    ROLE_SELECTOR: "select-role",
    DASHBOARD: "dashboard",
    USER_CONTROL: "user-control",
    USER_CONTROL_CREATE: "user-control/create",
    USER_CONTROL_EDIT: "user-control/:id/edit",
    FRANCHISES: "franchises",
    FRANCHISES_CREATE: "franchises/create",
    FRANCHISES_EDIT: "franchises/:id/edit",
    FRANCHISES_DETAIL: "franchises/:id",
    FRANCHISES_PRODUCT_ASSIGN: "franchises/:id/product-assign",
    SHIFTS: "shifts",
    INVENTORY: "inventory",
    INVENTORY_LOW_STOCK: "inventory/low-stock",
    CATEGORIES: "categories",
    CATEGORIES_CREATE: "categories/create",
    CATEGORIES_EDIT: "categories/:id/edit",
    PRODUCTS: "products",
    PRODUCTS_CREATE: "products/create",
    PRODUCTS_EDIT: "products/:id/edit",
    PRODUCTS_DETAIL: "products/:id",
    PROMOTIONS: "promotions",
    VOUCHERS: "vouchers",
    LOYALTY_RULES: "loyalty-rules",
    USER_FRANCHISE_ROLES: "user-franchise-roles",
    CUSTOMERS: "customers",
    CART: "cart",
    CART_CHECKOUT: "cart/:cartId/checkout",
  },
};
